[package]
name = "triangle"
version.workspace = true
edition.workspace = true

[dependencies]
env_logger = { workspace = true }
tokio = { workspace = true, features = ["full"] }
wgpu = { workspace = true }
winit = { workspace = true, features = ["rwh_06"] }
